---
- hosts: instance
  gather_facts: false
  pre_tasks:
    - name: Install Python
      raw: bash -c "test -e /usr/bin/python3 || (yum -y update && yum install -y python3) || (apt -y update && apt install -y python3)"
      retries: 10
      delay: 5
      register: result
      until: result.rc == 0
      changed_when: result.stdout != ""
    - action: setup
  roles:
    - common
