- name: setup additional nic cloudinit config
  copy:
    dest: /etc/cloud/cloud.cfg.d/99_exoscale_network.cfg
    content: |
      network:
        version: 1
        config:
      {% for ifname in hostvars[inventory_hostname]['ansible_interfaces'] %}
      {% set ifdata = hostvars[inventory_hostname]['ansible_%s' | format(ifname)] %}
      {% if ifdata['module'] is defined and ifdata['module'] == 'virtio_net' %}
        - type: physical
          name: {{ ifname }}
          subnets:
      {% if hostvars[inventory_hostname]['%s_address' | format(ifname)] is defined %}
            - type: static
              address: {{ hostvars[inventory_hostname]['%s_address' | format(ifname)] }}
      {% else %}
            - type: dhcp
      {% endif %}
      {% endif %}
      {% endfor %}
