- name: List physical network interfaces
  command: find /sys/class/net -type l -not -lname '*virtual*' -printf '%f\n'
  register: physical_interfaces

- name: setup additional nic cloudinit config
  copy:
    dest: /etc/cloud/cloud.cfg.d/99_exoscale_network.cfg
    content: |
      network:
        version: 1
        config:
      {% for ifname in physical_interfaces.stdout.split() %}
        - type: physical
          name: {{ ifname }}
          subnets:
      {% if hostvars[inventory_hostname]['%s_address' | format(ifname)] is defined %}
            - type: static
              address: {{ hostvars[inventory_hostname]['%s_address' | format(ifname)] }}
      {% else %}
            - type: dhcp
      {% endif %}
      {% endfor %}
